doctrine:
    orm:
        auto_generate_proxy_classes: false
# Temporarly disable this until this issue is resolved: https://github.com/symfony-tools/carsonbot/issues/179
#        metadata_cache_driver:
#            type: pool
#            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
