services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Api\Issue\CachedLabelsApi:
        class: App\Api\Issue\FakedCachedLabelApi

    App\Api\Status\StatusApi: '@App\Issues\NullStatusApi'
    App\Api\Issue\CommentsApiInterface: '@App\Api\Issue\NullCommentsApi'
